name: Deploy to EC2 Dev Instance

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run your deploy script
        id: deploy_step
        run: |
          echo "Running deploy script..."
          # simulate deployment
          sleep 5

      - name: Notify Google Chat
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          RUN_ID: ${{ github.run_id }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          STATUS="✅ Deployment Succeeded"
          if [ "$JOB_STATUS" != "success" ]; then
            STATUS="❌ Deployment Failed"
          fi

          cat <<EOF | curl -X POST "$WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d @-
          {
            "cardsV2": [
              {
                "card": {
                  "header": {
                    "title": "$STATUS",
                    "subtitle": "Commit by $ACTOR",
                    "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png",
                    "imageType": "CIRCLE"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "decoratedText": {
                            "text": "**Commit**: [$SHA](https://github.com/$REPO/commit/$SHA)"
                          }
                        },
                        {
                          "decoratedText": {
                            "text": "**Message**: $STATUS for job _deploy_"
                          }
                        }
                      ]
                    }
                  ],
                  "fixedFooter": {
                    "primaryButton": {
                      "text": "View Run",
                      "color": {
                        "red": 0,
                        "green": 0.5,
                        "blue": 1,
                        "alpha": 1
                      },
                      "onClick": {
                        "openLink": {
                          "url": "https://github.com/$REPO/actions/runs/$RUN_ID"
                        }
                      }
                    }
                  }
                }
              }
            ]
          }
