name: Deploy to EC2 Dev Instance

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit message
        id: get_commit
        run: |
          echo "message=$(git log -1 --pretty=format:%s)" >> $GITHUB_OUTPUT

      - name: Run your deploy script
        id: deploy_step
        run: |
          echo "Running deploy script..."
          # simulate deployment
          sleep 5

      - name: Notify Google Chat
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF_NAME: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}
          COMMIT_MSG: ${{ steps.get_commit.outputs.message }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          STATUS="✅ Deployment Succeeded"
          if [ "$JOB_STATUS" != "success" ]; then
            STATUS="❌ Deployment Failed"
          fi

          cat <<EOF | curl -X POST "$WEBHOOK_URL" \
            -H 'Content-Type: application/json' \
            -d @-
          {
            "cardsV2": [
              {
                "card": {
                  "header": {
                    "title": "$STATUS",
                    "subtitle": "Commit by $ACTOR on branch $REF_NAME",
                    "imageUrl": "https://developers.google.com/chat/images/quickstart-app-avatar.png",
                    "imageType": "CIRCLE"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "decoratedText": {
                            "text": "**Commit**: [$SHA](https://github.com/$REPO/commit/$SHA)"
                          }
                        },
                        {
                          "decoratedText": {
                            "text": "**Branch**: $REF_NAME"
                          }
                        },
                        {
                          "decoratedText": {
                            "text": "**Message**: $COMMIT_MSG"
                          }
                        },
                        {
                          "buttonList": {
                            "buttons": [
                              {
                                "text": "View Commit",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/$REPO/commit/$SHA"
                                  }
                                }
                              },
                              {
                                "text": "View Workflow",
                                "onClick": {
                                  "openLink": {
                                    "url": "https://github.com/$REPO/actions/runs/$RUN_ID"
                                  }
                                }
                              }
                            ]
                          }
                        }
                      ]
                    }
                  ]
                }
              }
            ]
          }
